
Chat.BLACK = "§0"
Chat.DARK_BLUE = "§1"
Chat.DARK_GREEN = "§2"
Chat.DARK_AQUA = "§3"
Chat.DARK_RED = "§4"
Chat.DARK_PURPLE = "§5"
Chat.GOLD = "§6"
Chat.GRAY = "§7"
Chat.DARK_GRAY = "§8"
Chat.BLUE = "§9"
Chat.GREEN = "§a"
Chat.AQUA = "§b"
Chat.RED = "§c"
Chat.LIGHT_PURPLE = "§d"
Chat.YELLOW = "§e"
Chat.WHITE = "§f"

Chat.OBFUSCATED = "§k"
Chat.BOLD = "§l"
Chat.UNDERLINE = "§n"
Chat.ITALIC = "§o"
Chat.RESET = "§r"
